name: Lint
on:
  push:
    paths: ['*.py']
  workflow_dispatch:

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
          architecture: x64
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
